name: Test Testcases

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Create .env File
        run: |
          echo "BASE_URL=${{ secrets.BASE_URL }}" >> .env
          echo "USERNAME=${{ secrets.BASE_UNAME }}" >> .env
          echo "PASSWORD=${{ secrets.PASSWORD }}" >> .env
          echo "HEADLESS=${{ secrets.HEADLESS }}" >> .env
          echo "TIMEOUT=${{ secrets.TIMEOUT }}" >> .env
          echo "PKG_CONFIG=${{ secrets.PKG_CONFIG }}" >> .env
          echo "PKG_TRANS=${{ secrets.PKG_TRANS }}" >> .env
          echo "REL_MMGT=${{ secrets.REL_MMGT }}" >> .env

      - name: Install Packages
        run: pip install -r requirements.txt

      - name: Install PlaywRight
        run: playwright install --with-deps

      - name: Run Test
        run: pytest --browser chromium --ignore-https-errors
